#!/usr/bin/python3

from cycler import cycler
import argparse
import sys
import os
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

def create_arg_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('file')
    parser.add_argument('--save', action='store_true')


    return parser



colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan']

def legend(name, param):
    if "Im" in name:
        return f"Im et al. (ε = {param})"
    elif "PRR" in name:
        return f"PRR (λ = {param})"
    else:
        return "Round-Robin"


def plot(filename, save):
    df = pd.read_csv(filename)
    df = df.round(3)
    df['cr'] = df['alg'] / df['opt']
    df['param'] = df[['name','param']].apply(lambda x: legend(*x),axis=1)
    sns.set_theme(style='white')

    ax = sns.lineplot(data=df, x="round", y="cr", hue='param', style='name',markers=True)
    plt.legend(labels=df['param'].unique())
    

    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    plt.xlabel('Round')
    plt.ylabel('Empirical competitive ratio')
    plt.tight_layout()
    #plt.axis([0, max_bin, 0.99, 1.1])


    fig = plt.gcf()
    fig.set_dpi(300)
    fig.set_size_inches(3,2)

    if save:
        f = filename.split(".")[0]
        plt.savefig(f"{f}.pdf")
    else:
        plt.show()


if __name__ == "__main__":
    arg_parser = create_arg_parser()
    parsed_args = arg_parser.parse_args(sys.argv[1:])
    if os.path.exists(parsed_args.file):
        plot(parsed_args.file, parsed_args.save)

    else:
        print("Path not valid!")
