#!/usr/bin/python3

from cycler import cycler
import argparse
import sys
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def create_arg_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('file')
    parser.add_argument('-l', '--lambdas', nargs="+", default=[0.0, 0.25, 0.5, 0.75, 1.0])


    return parser


def get_data(filename):
    data = pd.read_csv(filename)
    data = data.round(3)
    data['prr_cr'] = data['prr'] / data['opt']
    return data


colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan']


def plot(df, args):
    plt.figure()

    df = df[df['lambda'].isin(args.lambdas)]
    df_prr = df.loc[:, ['lambda', 'round', 'prr_cr']]

    plt.rc('axes', prop_cycle=(cycler('color', colors[0:len(args.lambdas)])))

    grouped_data = df_prr.groupby(['lambda', 'round']).mean().unstack('lambda')
    for label, l in list(grouped_data):
        grouped_data[(label, l)].plot(
            style='-', markersize=0, linewidth=1.2, label=f"PRR (λ = {l:1.2f})", legend=True)

    #plt.plot((0, max_bin), (1, 1), 'black')
    plt.xlabel('round')
    plt.ylabel('Empirical competitive ratio')
    plt.legend()
    plt.tight_layout()
    #plt.axis([0, max_bin, 0.99, 1.1])


    fig = plt.gcf()
    fig.set_dpi(500)
    fig.set_size_inches(4,2.5)
    # fig.subplots_adjust(right=0.7)
    #fig.savefig("result.png", dpi=400)


if __name__ == "__main__":
    arg_parser = create_arg_parser()
    parsed_args = arg_parser.parse_args(sys.argv[1:])
    if os.path.exists(parsed_args.file):

        data = get_data(parsed_args.file)
        plot(data, parsed_args)

        plt.show()
    else:
        print("Path not valid!")
